<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="3" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-07T08:16:23 IST" name="Suite" finished-at="2025-01-07T08:17:00 IST" duration-ms="37028">
    <groups>
      <group name="PlaceOrderTest">
        <method signature="PlaceOrderTest.SubmitOrderTest(java.util.HashMap)[pri:0, instance:seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]" name="SubmitOrderTest" class="seleniumFrameworkPractice.refactor.tests.PlaceOrderTest"/>
      </group> <!-- PlaceOrderTest -->
      <group name="ErrorHandlings">
        <method signature="ErrorValidations.incorrectCredentialsTest()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.ErrorValidations@79defdc]" name="incorrectCredentialsTest" class="seleniumFrameworkPractice.refactor.tests.ErrorValidations"/>
      </group> <!-- ErrorHandlings -->
    </groups>
    <test started-at="2025-01-07T08:16:23 IST" name="ErrorValidations" finished-at="2025-01-07T08:16:32 IST" duration-ms="9676">
      <class name="seleniumFrameworkPractice.refactor.tests.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.ErrorValidations@79defdc]" started-at="2025-01-07T08:16:23 IST" name="launchApplication" finished-at="2025-01-07T08:16:30 IST" duration-ms="6911" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="incorrectCredentialsTest()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.ErrorValidations@79defdc]" started-at="2025-01-07T08:16:30 IST" name="incorrectCredentialsTest" finished-at="2025-01-07T08:16:30 IST" duration-ms="761" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ Incorrect email or password] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ Incorrect email or password] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at seleniumFrameworkPractice.refactor.tests.ErrorValidations.incorrectCredentialsTest(ErrorValidations.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectCredentialsTest -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.ErrorValidations@79defdc]" started-at="2025-01-07T08:16:31 IST" name="closeApplication" finished-at="2025-01-07T08:16:32 IST" duration-ms="1338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- seleniumFrameworkPractice.refactor.tests.ErrorValidations -->
    </test> <!-- ErrorValidations -->
    <test started-at="2025-01-07T08:16:23 IST" name="PlaceOrderTest" finished-at="2025-01-07T08:17:00 IST" duration-ms="37028">
      <class name="seleniumFrameworkPractice.refactor.tests.PlaceOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]" started-at="2025-01-07T08:16:23 IST" name="launchApplication" finished-at="2025-01-07T08:16:30 IST" duration-ms="6618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrderTest(java.util.HashMap)[pri:0, instance:seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]" started-at="2025-01-07T08:16:30 IST" name="SubmitOrderTest" data-provider="getDatabyJson" finished-at="2025-01-07T08:16:46 IST" duration-ms="16471" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sura@1234, product_Name=ADIDAS ORIGINAL, username=Surendhar@selenium.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at seleniumFrameworkPractice.refactor.tests.PlaceOrderTest.SubmitOrderTest(PlaceOrderTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrderTest -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]" started-at="2025-01-07T08:16:46 IST" name="closeApplication" finished-at="2025-01-07T08:16:48 IST" duration-ms="1345" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]" started-at="2025-01-07T08:16:48 IST" name="launchApplication" finished-at="2025-01-07T08:16:53 IST" duration-ms="5201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrderTest(java.util.HashMap)[pri:0, instance:seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]" started-at="2025-01-07T08:16:53 IST" name="SubmitOrderTest" data-provider="getDatabyJson" finished-at="2025-01-07T08:16:58 IST" duration-ms="5229" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sura@1234, product_Name=BANARSI SAREE, username=sura@test.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Thankyou for the order.] but found [THANKYOU FOR THE ORDER.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at seleniumFrameworkPractice.refactor.tests.PlaceOrderTest.SubmitOrderTest(PlaceOrderTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrderTest -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]" started-at="2025-01-07T08:16:58 IST" name="closeApplication" finished-at="2025-01-07T08:17:00 IST" duration-ms="1350" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
        <test-method signature="OrderpageProductValidation()[pri:0, instance:seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]" started-at="2025-01-07T08:17:00 IST" name="OrderpageProductValidation" finished-at="2025-01-07T08:17:00 IST" depends-on-methods="seleniumFrameworkPractice.refactor.tests.PlaceOrderTest.SubmitOrderTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method seleniumFrameworkPractice.refactor.tests.PlaceOrderTest.OrderpageProductValidation() on instance seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d depends on not successfully finished methods 
[seleniumFrameworkPractice.refactor.tests.PlaceOrderTest.SubmitOrderTest() on instance seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method seleniumFrameworkPractice.refactor.tests.PlaceOrderTest.OrderpageProductValidation() on instance seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d depends on not successfully finished methods 
[seleniumFrameworkPractice.refactor.tests.PlaceOrderTest.SubmitOrderTest() on instance seleniumFrameworkPractice.refactor.tests.PlaceOrderTest@58e1d9d]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderpageProductValidation -->
      </class> <!-- seleniumFrameworkPractice.refactor.tests.PlaceOrderTest -->
    </test> <!-- PlaceOrderTest -->
  </suite> <!-- Suite -->
</testng-results>
